import {
  Brain,
  Sparkles,
  BookOpen,
  Layers,
  Grid,
  Eye,
  Hash,
  Volume2,
  Coffee,
  Flame,
  Sun,
  Bell,
  Feather,
  Music,
  CheckCircle2,
  Clock,
  Heart,
  Activity,
  AlertTriangle,
  User,
  Phone,
  Calendar,
  CloudSun,
  Wifi,
  WifiOff,
  ChevronRight,
  ChevronLeft,
  Play,
  RotateCcw,
  VolumeX,
  Mic,
  MessageSquare,
  FileText,
  Settings,
  Shield,
  Stethoscope,
  TrendingDown,
  TrendingUp,
  Award,
  Share2,
  Check,
  Puzzle,
  Search,
  Palette,
  Home,
  Compass,
  ListOrdered,
  Footprints,
  Armchair,
  Hand,
  Square,
  RotateCw,
  Shuffle
} from "lucide-react";
export const IconHelper = ({ name, className = "w-5 h-5", size }) => {
  const iconMap = {
    Brain: <Brain className={className} size={size} />,
    Sparkles: <Sparkles className={className} size={size} />,
    BookOpen: <BookOpen className={className} size={size} />,
    Layers: <Layers className={className} size={size} />,
    Grid: <Grid className={className} size={size} />,
    Eye: <Eye className={className} size={size} />,
    Hash: <Hash className={className} size={size} />,
    Volume2: <Volume2 className={className} size={size} />,
    Coffee: <Coffee className={className} size={size} />,
    Flame: <Flame className={className} size={size} />,
    Sun: <Sun className={className} size={size} />,
    Bell: <Bell className={className} size={size} />,
    Feather: <Feather className={className} size={size} />,
    Music: <Music className={className} size={size} />,
    CheckCircle2: <CheckCircle2 className={className} size={size} />,
    Clock: <Clock className={className} size={size} />,
    Heart: <Heart className={className} size={size} />,
    Activity: <Activity className={className} size={size} />,
    AlertTriangle: <AlertTriangle className={className} size={size} />,
    User: <User className={className} size={size} />,
    Phone: <Phone className={className} size={size} />,
    Calendar: <Calendar className={className} size={size} />,
    CloudSun: <CloudSun className={className} size={size} />,
    Wifi: <Wifi className={className} size={size} />,
    WifiOff: <WifiOff className={className} size={size} />,
    ChevronRight: <ChevronRight className={className} size={size} />,
    ChevronLeft: <ChevronLeft className={className} size={size} />,
    Play: <Play className={className} size={size} />,
    RotateCcw: <RotateCcw className={className} size={size} />,
    VolumeX: <VolumeX className={className} size={size} />,
    Mic: <Mic className={className} size={size} />,
    MessageSquare: <MessageSquare className={className} size={size} />,
    FileText: <FileText className={className} size={size} />,
    Settings: <Settings className={className} size={size} />,
    Shield: <Shield className={className} size={size} />,
    Stethoscope: <Stethoscope className={className} size={size} />,
    TrendingDown: <TrendingDown className={className} size={size} />,
    TrendingUp: <TrendingUp className={className} size={size} />,
    Award: <Award className={className} size={size} />,
    Share2: <Share2 className={className} size={size} />,
    Check: <Check className={className} size={size} />,
    Puzzle: <Puzzle className={className} size={size} />,
    Search: <Search className={className} size={size} />,
    Palette: <Palette className={className} size={size} />,
    Home: <Home className={className} size={size} />,
    Compass: <Compass className={className} size={size} />,
    ListOrdered: <ListOrdered className={className} size={size} />,
    Footprints: <Footprints className={className} size={size} />,
    Armchair: <Armchair className={className} size={size} />,
    Hand: <Hand className={className} size={size} />,
    Square: <Square className={className} size={size} />,
    RotateCw: <RotateCw className={className} size={size} />,
    Shuffle: <Shuffle className={className} size={size} />
  };
  return iconMap[name] || <Brain className={className} size={size} />;
};
